Homework 7
Otus-DevOps-2023-07/MaxDamage81_infra pull request #6
Opened 2023-09-21 11:13 UTC by MaxDamage81

# Выполнено ДЗ №

 - [V] Основное ДЗ
 - [V] Задание со *
 - [ ] Задание с **

## В процессе сделано:
- Create new packer image
- Create APP and DB modules
- Create stage and prod env.
- Create S3 storage
- Configure backend to S3
- Check tfstate file in S3 storage

## Как запустить проект:
 - Run terraform apply

## Как проверить работоспособность:
 - Task with ** is not completed =(

## PR checklist
 - [V] Выставил label с номером домашнего задания
 - [V] Выставил label с темой домашнего задания

2023-09-23 10:15 UTC, mrgreyves approved these changes
Здравствуйте!)
Уууупс, и я случайно нажад не на ту кнопку =(
Вам нужно свериться с результатами тестов и поправить некоторые файлы

2023-09-23 10:17 UTC, mrgreyves requested changes
UPD

2023-09-24 15:20 UTC, MaxDamage81 commented
@mrgreyves Здравствуйте. Результаты теста довольно странные. В задании не было указано, то необходимы json файлы и отдельный модуль vpc. Переделал в json + вынес vpc в отдельный модуль. Однако проблема с неверной версией терраформа остаётся. 
```
 +Error: Invalid version constraint
     +
     +  on main.tf line 3, in terraform:
     +   3:     yandex = {
     +   4:       source  = "yandex-cloud/yandex"
     +   5:       version = "0.95.0"
     +   6:     }
     +
     +A string value is required for yandex.
```
Прошу помочь в решении данной проблемы. Дело явно в автотесте, т.к. проект работает (кроме задания с **)

2023-09-26 20:30 UTC, mrgreyves approved these changes
Здравствуйте!)
Да, вы правы и я писал ранее
Тут сыграла особенность определения провайдера
Вы используете более новую версию терраформа где изменилось определение
С дз у вас хорошо, апрув ^_^

2023-09-27 13:31 UTC, merged